name: Build packages

on:
  - push
  - pull_request

jobs:
  cache-and-install:
    name: Build packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        uses: mansagroup/nrwl-nx-action@v3.2.2
        with:
          targets: build
          all: 'true'